@host = http://localhost:5162

### Get settings
GET {{host}}/api/settings

### Upload file
POST {{host}}/api/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test.wav"
Content-Type: audio/wav

< ./test.wav
--boundary--

### Check job status
GET {{host}}/api/status/abc123
